### ISSUE TITLE
Can't install predictiveness-curve module from testpypi

### ISSUE THREAD

**Issue by yamasakih** [yamasakih/predictiveness-curve#68]
```shell
% pip install -i https://test.pypi.org/simple/ predictiveness-curve
Looking in indexes: https://test.pypi.org/simple/
Collecting predictiveness-curve
  Downloading https://test-files.pythonhosted.org/packages/9c/21/525ff1a6464a15057427f432ce511bc4d2568d1d7697ffce0df02f44db74/predictiveness-curve-0.2.2.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/62/g029th7j73bd1vc5b4dtrf2w0000gn/T/pip-install-pxv79gj7/predictiveness-curve/setup.py", line 3, in <module>
        setup()
      File "/Users/yamasakih/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/Users/yamasakih/anaconda3/lib/python3.6/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/Users/yamasakih/anaconda3/lib/python3.6/site-packages/setuptools/dist.py", line 485, in parse_config_files
        ignore_option_errors=ignore_option_errors)
      File "/Users/yamasakih/anaconda3/lib/python3.6/site-packages/setuptools/config.py", line 106, in parse_configuration
        meta.parse()
      File "/Users/yamasakih/anaconda3/lib/python3.6/site-packages/setuptools/config.py", line 382, in parse
        section_parser_method(section_options)
      File "/Users/yamasakih/anaconda3/lib/python3.6/site-packages/setuptools/config.py", line 355, in parse_section
        self[name] = value
      File "/Users/yamasakih/anaconda3/lib/python3.6/site-packages/setuptools/config.py", line 173, in __setitem__
        value = parser(value)
      File "/Users/yamasakih/anaconda3/lib/python3.6/site-packages/setuptools/config.py", line 430, in _parse_version
        version = self._parse_attr(value)
      File "/Users/yamasakih/anaconda3/lib/python3.6/site-packages/setuptools/config.py", line 305, in _parse_attr
        module = import_module(module_name)
      File "/Users/yamasakih/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'predictiveness_curve'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/62/g029th7j73bd1vc5b4dtrf2w0000gn/T/pip-install-pxv79gj7/predictiveness-curve/
```

**Comment by yamasakih** [comment]
Can't find `predictiveness_curve.__version__`?

**Comment by kubor** [comment]
`__init__.py` で import してる部分で失敗しちゃってますね。
どうしようかな。

**Comment by yamasakih** [comment]
@kubor Thx, your comment :)  
I try to write as follows code referring to flask:

```python
import io
import re


with io.open('predictiveness_curve/__init__.py', 'rt', encoding='utf8') as f:
    version = re.search(r"__version__ = '(.*?)'", f.read()).group(1)
```

Ref. https://github.com/pallets/flask/blob/master/setup.py

**Comment by yamasakih** [comment]
mmm...

```shell
% pip install -i https://test.pypi.org/simple/ predictiveness-curve==0.2.2b1
Looking in indexes: https://test.pypi.org/simple/
Collecting predictiveness-curve==0.2.2b1
  Downloading https://test-files.pythonhosted.org/packages/3f/11/0c1ae2bfea9fa8b42313b4a4b242d1193989c662c43bca9ae4ba375a2421/predictiveness-curve-0.2.2b1.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/62/g029th7j73bd1vc5b4dtrf2w0000gn/T/pip-install-h018gxa9/predictiveness-curve/setup.py", line 5, in <module>
        with io.open('predictiveness_curve/__init__.py', 'rt', encoding='utf8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'predictiveness_curve/__init__.py'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/62/g029th7j73bd1vc5b4dtrf2w0000gn/T/pip-install-h018gxa9/predictiveness-curve/
```

**Comment by yamasakih** [comment]
Added above codes. 0df184b

**Comment by yamasakih** [comment]
mmm...

```shell
% pip install -i https://test.pypi.org/simple/ predictiveness-curve==0.2.2b1
Looking in indexes: https://test.pypi.org/simple/
Collecting predictiveness-curve==0.2.2b1
  Downloading https://test-files.pythonhosted.org/packages/3f/11/0c1ae2bfea9fa8b42313b4a4b242d1193989c662c43bca9ae4ba375a2421/predictiveness-curve-0.2.2b1.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/62/g029th7j73bd1vc5b4dtrf2w0000gn/T/pip-install-h018gxa9/predictiveness-curve/setup.py", line 5, in <module>
        with io.open('predictiveness_curve/__init__.py', 'rt', encoding='utf8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'predictiveness_curve/__init__.py'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/62/g029th7j73bd1vc5b4dtrf2w0000gn/T/pip-install-h018gxa9/predictiveness-curve/
```

**Comment by yamasakih** [comment]
```python
# Get __version__ variable
exec(open(os.path.join(here, 'chainer_chemistry', '_version.py')).read())
```

Ref. https://github.com/pfnet-research/chainer-chemistry/blob/master/setup.py

**Comment by zaltoprofen** [comment]
ここが誤っています。
https://github.com/yamasakih/predictiveness-curve/blob/0df184bdb1b6e5a726bb4cfc278c299827516649/setup.cfg#L13

`py_modules` ではなく `packages` にすることで sdist を実行したときに `predictiveness_curve` も正しく tarball に配置されることを確認しました。

cf. `py_modules` vs `packages` - https://docs.python.org/ja/3/distutils/examples.html

**Comment by yamasakih** [comment]
@zaltoprofen Brilliant!! 💎 Thx :)

I just noticed that `base.py` and `__init__.py` are not copied.

Now, I changed `setup.cfg` according with your advice, then it did copyed both them. 🎉 

```shell
% python setup.py sdist                                                                                                                   (git)-[bugfix/import-version-info]
running sdist
running egg_info
writing predictiveness_curve.egg-info/PKG-INFO
writing dependency_links to predictiveness_curve.egg-info/dependency_links.txt
writing requirements to predictiveness_curve.egg-info/requires.txt
writing top-level names to predictiveness_curve.egg-info/top_level.txt
reading manifest file 'predictiveness_curve.egg-info/SOURCES.txt'
writing manifest file 'predictiveness_curve.egg-info/SOURCES.txt'
running check
creating predictiveness-curve-0.2.2b2
creating predictiveness-curve-0.2.2b2/predictiveness_curve
creating predictiveness-curve-0.2.2b2/predictiveness_curve.egg-info
copying files to predictiveness-curve-0.2.2b2...
copying README.md -> predictiveness-curve-0.2.2b2
copying setup.cfg -> predictiveness-curve-0.2.2b2
copying setup.py -> predictiveness-curve-0.2.2b2
copying predictiveness_curve/__init__.py -> predictiveness-curve-0.2.2b2/predictiveness_curve
copying predictiveness_curve/base.py -> predictiveness-curve-0.2.2b2/predictiveness_curve
copying predictiveness_curve.egg-info/PKG-INFO -> predictiveness-curve-0.2.2b2/predictiveness_curve.egg-info
copying predictiveness_curve.egg-info/SOURCES.txt -> predictiveness-curve-0.2.2b2/predictiveness_curve.egg-info
copying predictiveness_curve.egg-info/dependency_links.txt -> predictiveness-curve-0.2.2b2/predictiveness_curve.egg-info
copying predictiveness_curve.egg-info/requires.txt -> predictiveness-curve-0.2.2b2/predictiveness_curve.egg-info
copying predictiveness_curve.egg-info/top_level.txt -> predictiveness-curve-0.2.2b2/predictiveness_curve.egg-info
Writing predictiveness-curve-0.2.2b2/setup.cfg
Creating tar archive
removing 'predictiveness-curve-0.2.2b2' (and everything under it)
```

**Comment by yamasakih** [comment]
Fix setup.cfg. 3d6859b

**Comment by yamasakih** [comment]
Updated setup.cfg and .travis.yml. https://github.com/yamasakih/predictiveness-curve/pull/69/commits/2a2bf134db5e3327e240f474220268a725e11ccb

**Comment by yamasakih** [comment]
It worked. Thx, everyone! :)
